# The key combination used to send commands to tmux.
unbind-key C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# Use vi key bindings in copy mode
set-option -wg mode-keys vi

# Use vi key bindings to navigate between the panes
unbind-key -T prefix Up
bind-key -r -T prefix k select-pane -U

unbind-key -T prefix Down
bind-key -r -T prefix j select-pane -D

unbind-key -T prefix Left
bind-key -r -T prefix h select-pane -L

unbind-key -T prefix Right
bind-key -r -T prefix l select-pane -R

# Copy to clipboard using 'y' in copy mode
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Configure selection using 'v' in copy mode
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send-keys -X begin-selection

unbind-key -T copy-mode-vi Space
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 

# Switch windows using Alt + Number without prefix
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

# Source tmux config with R
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "source-file done"
