# Use system clipboard
set -g set-clipboard on

# Enable mouse support: click to select panes/windows, scroll, resize panes.
set -g mouse on

# Starting index for window numbers. 1 is more ergonomic for keyboard switching.
set -g base-index 1

# Starting index for pane numbers within windows.
setw -g pane-base-index 1

# Renumber windows
set -g renumber-windows on

# Number of lines to keep in scrollback buffer per pane.
set -g history-limit 1000000

# Update status bar in every 3 seconds
set -g status-interval 3

# Allow programs in the pane to bypass tmux (e.g. for image preview)
set -g allow-passthrough on

# Message display time (in milliseconds)
set -g display-time 2500

# Set default terminal to "tmux-256color"
set -g default-terminal "tmux-256color"

# Enable focus events
set -g focus-events on
