# Dracula color palette
midnight_express="#282A36"
chetwode_blue="#6272A4"
blue_zodiac="#44475A"
ivory="#F8F8F2"
flourescent_red="#FF5555"
desert_dessert="#FFB86C"
pineapple_perfume="#F1FA8C"
bright_neon_green="#50FA7B"
light_pastel="#8BE9FD"
biloba_flower="#BD93F9"
magenta_pink="#FF79C6"

# Reused items
tmux_icon="#[fg=${midnight_express},bg=${bright_neon_green}]   #{session_name}"

# Configure status bar
set -g status-style "fg=${ivory},bg=${midnight_express}"
set -g status-left "${tmux_icon} "
set -g status-right "#[fg=${midnight_express},bg=${light_pastel}] %A, %d %b #[fg=${midnight_express},bg=${biloba_flower}] %I:%M %p "

set -g window-status-current-format "#[fg=${ivory}]  #{window_index} #{window_name} "
set -g window-status-current-style "bg=${chetwode_blue}"
set -g window-status-format "#[fg=${ivory}]  #{window_index} #{window_name} "
set -g window-status-separator "  "

set -g message-command-style "bg=${blue_zodiac},fg=${ivory}"
set -g message-format "${tmux_icon} #[bg=${desert_dessert}]     #{message} "
set -g message-style "bg=${desert_dessert},fg=${midnight_express}"
